import Head from 'next/head'
import { PostCard } from '../components'
import myData from '../assets/data.json'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Sociality</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <PostCard post={myData.posts_by_date} />
      </main>
    </div>
  )
}
